@startuml
'https://plantuml.com/sequence-diagram
class Output {

main()

}

class WordFinder {

String fileName;
String fileDestination;
String target;
String replacement;

String replaceTextFile()

}

Output <--o WordFinder
@enduml